name: Build and Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x', '22.x', '24.x']
        trpc-version: ['10', '11']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v3
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Install tRPC version ${{ matrix.trpc-version }}
        run: pnpm add -D @trpc/server@${{ matrix.trpc-version }}
      - name: Lint
        run: pnpm check:format
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
